#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# If a command in a pipeline fails, 
# return the status of the last command to exit with a non-zero status.
set -o pipefail

# Treat unset variables as an error and exit immediately.
set -o nounset

# Function to check if PostgreSQL is ready to accept connections.
postgres_ready() { 
    python << END
import sys
import psycopg2

    try:
        psycopg2.connect(
            dbname='${POSTGRES_DB}',
            user='${POSTGRES_USER}',
            password='${POSTGRES_PASSWORD}',
            host='${PG_HOST}',
            port='${PG_PORT}',
        )
    except psycopg2.OperationalError:
        sys.exit(-1)
    
    sys.exit(0) 
END 
}

until postgres_ready; do
 >&2 echo "Waiting for PostgreSQL to run..."
 sleep 1
done
 >&2 echo "PostgreSQL is ready."

# Execute the command passed as arguments to this script.
exec "$@"