#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# If a command in a pipeline fails, 
# return the status of the last command to exit with a non-zero status.
set -o pipefail

# Treat unset variables as an error and exit immediately.
set -o nounset

python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000